_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/train.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 11
                - 30
                - 41
                - 49
                - 51
                - 55
                - 71
                - 84
                - 95
                - 98
            "3":
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
