[project]
name = "grpo-weave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.6.0",
    "datasets>=3.5.0",
    "simple-parsing>=0.1.7",
    "sympy>=1.13.1",
    "trl>=0.17.0.dev0",
]
