model_name: Qwen/Qwen3-4B

dataset_name: gsm8k_dataset_prepared

# GRPO trainer config
bf16: true
use_vllm: true
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen3-4B-Simple-RL
hub_strategy: end
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 1024
max_steps: -1
num_generations: 16
num_train_epochs: 1
output_dir: data/Qwen3-4B-Simple-RL
overwrite_output_dir: true
per_device_train_batch_size: 16
push_to_hub: true
report_to:
- wandb
# reward_funcs:
# - accuracy
# - format
# reward_weights:
# - 1.0
# - 1.0
save_strategy: "no"
seed: 42
warmup_ratio: 0.1